#! /bin/sh

pgrep sxhkd > /dev/null || sxhkd &
setxkbmap hu
~/.fehbg

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 
#bspc monitor DP2-2 -d 4 5 6 
#bspc monitor DP2-3 -d 7 8 9

bspc config border_width                  3
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a guake state=floating follow=on
bspc rule -a Guake state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Deluge desktop='^9'
bspc rule -a gedit state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a blueman-manager state=floating

~/.config/polybar/launch.sh

